# Site settings
title: Code Blocker
header-img: img/home-bg.png
email: keonilrath@gmail.com
copyright_name: zenglue
description: > # this means to ignore newlines until "baseurl:"
  A Journey in Back End Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zenglue
learn_profile: zenglue
email_username: keonilrath@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
